// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9nBNih0NfAqoG-EJ6wcSaRdrnxNe0HVA',
    appId: '1:316417505114:web:b4c5d8312e015349922563',
    messagingSenderId: '316417505114',
    projectId: 'mental-zen-dev',
    authDomain: 'mental-zen-dev.firebaseapp.com',
    storageBucket: 'mental-zen-dev.firebasestorage.app',
    measurementId: 'G-8DTW5H5NMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTtii5ts6oE-bFOA8-4DqEAnUM63F1PdI',
    appId: '1:316417505114:android:bc82ab2be9c03ebe922563',
    messagingSenderId: '316417505114',
    projectId: 'mental-zen-dev',
    storageBucket: 'mental-zen-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYp9cHLpo1aDcqBcmcJuQl4-lYSfWwbg',
    appId: '1:316417505114:ios:e77fe3fc4fdafd74922563',
    messagingSenderId: '316417505114',
    projectId: 'mental-zen-dev',
    storageBucket: 'mental-zen-dev.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwYp9cHLpo1aDcqBcmcJuQl4-lYSfWwbg',
    appId: '1:316417505114:ios:e77fe3fc4fdafd74922563',
    messagingSenderId: '316417505114',
    projectId: 'mental-zen-dev',
    storageBucket: 'mental-zen-dev.firebasestorage.app',
    iosBundleId: 'com.example.mentalZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9nBNih0NfAqoG-EJ6wcSaRdrnxNe0HVA',
    appId: '1:316417505114:web:1ce98f6aaa8a1b82922563',
    messagingSenderId: '316417505114',
    projectId: 'mental-zen-dev',
    authDomain: 'mental-zen-dev.firebaseapp.com',
    storageBucket: 'mental-zen-dev.firebasestorage.app',
    measurementId: 'G-WM4E22LX9M',
  );
}
